<div class="bg-white">
    <x-modal-html modalId="userOptionalBoxModal" :width="$width">
        @if ($componentName == 'change-offer-for-user')
            @livewire('change-offer-for-user')
        @elseif($componentName == 'change-offer-for-collection-of-users')
            @livewire('change-offer-for-collection-of-users')
        @elseif($componentName == 'edit-expired-date-for-users')
            @livewire('edit-expired-date-for-user')
        @elseif($componentName == 'edit-expired-date-for-collection')
            @livewire('edit-expired-date-for-collection')
        @elseif($componentName == 'users.renew')
            @livewire('users.renew')
        @elseif($componentName == 'users.renew-all')
            @livewire('users.renew-all')
        @elseif($componentName == 'users.show-quta-usage')
            @livewire('users.show-quta-usage')
        @elseif($componentName == 'show-user-invoices')
            @livewire('show-user-invoices')
        @elseif($componentName == 'show-user-log')
            @livewire('show-user-log')
        @elseif($componentName == 'show-and-add-quta-for-user')
            @livewire('show-and-add-quta-for-user')
        @elseif($componentName == 'edit-user-panel-password')
            @livewire('edit-user-panel-password')
        @elseif($componentName == 'edit-quta-for-collection')
            @livewire('edit-quta-for-collection')
        @elseif($componentName == 'show-and-edit-user-macs')
            @livewire('show-and-edit-user-macs')
        @elseif($componentName == 'move-users-to-nas')
            @livewire('move-users-to-nas')
        @elseif($componentName == 'edit-view-columns')
            @livewire('edit-view-columns')
        @elseif($componentName == 'admin-messages.send-admin-message-to-user')
            @livewire('admin-messages.send-admin-message-to-user')
        @endif
    </x-modal-html>
</div>
